apps:
  - name: app-shortvideo
    script: server/app.js
    exec_mode: fork
    interpreter: node
    instances: 1
    instance_var: INSTANCE_ID
    error: logs/pm2-error.log
    output: logs/pm2-out.log
    merge_logs: true
